End point to register new applicants & trigger mail to applicant
AltCampus/orbit pull request #11
Opened 2019-11-22 10:53 UTC by prarora98

2019-11-22 16:42 UTC, singhabhinav96 commented
Tested and looks good.

2019-11-23 04:18 UTC, prank7 requested changes
@prarora98 @Ckbhatia please check the review, correct and update the PR

2019-11-23 04:18 UTC, prank7 commented on routes/user.js
> +      const UpdatedUser = await user.save();
Should be updatedUser and not UpdatedUser. Caps is used only for global variables.

2019-11-23 04:18 UTC, prank7 commented on routes/user.js
> +      return res.status(201).json({ status: true, UpdatedUser });
The response should be 

`res.status(201).json({ status: true, user: updatedUser });`

Always send consistent key in response object.

2019-11-23 04:39 UTC, merged

2019-11-23 04:39 UTC, prank7 commented
close #11