Redux integration
AltCampus/orbit pull request #21
Opened 2019-12-04 04:24 UTC by Ckbhatia

One issue persists, login doesn't redirect the user to the dashboard page.

2019-12-04 04:36 UTC, prank7 requested changes

2019-12-04 04:36 UTC, prank7 commented on client/App.js
> +      // const token = JSON.parse(localStorage.getItem("authToken"));
Protected routes are not configured properly.

2019-12-04 04:36 UTC, prank7 commented on client/components/login/Login.js
>    handleSubmit = e => {
Where is the state?

2019-12-05 08:54 UTC, Ckbhatia commented on client/components/login/Login.js
>    handleSubmit = e => {
Solved

2019-12-05 08:59 UTC, merged